name = "vyasa"
description = "Static site generator"
version = "0.1.0-dev"

authors = ["Max Reznik"]
maintainers = ["Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
licenses = "Apache-2.0 WITH LLVM-exception"
website = ""
tags = ["markdown", "html", "generator"]

executables = ["vyasa"]

[build-switches]
development.optimization = ["-O0"]
development.style_checks = ["-gnaty"]
development.contracts = "Yes"
"*".ada_version = "Ada2022"

[[depends-on]]
markdown = "^26.0.0"
